include $(TOPDIR)/rules.mk

PKG_NAME:=ffka-india-client-psk
PKG_VERSION:=1
PKG_RELEASE:=1

include $(TOPDIR)/../package/gluon.mk

define Package/ffka-india-client-psk
  TITLE:=ffka-india-client-psk
  DEPENDS:=+gluon-core
endef

$(eval $(call BuildPackageGluon,ffka-india-client-psk))
